import { useState, useEffect, useRef } from 'react'
import './App.css'
import { restaurants, getRandomRestaurant } from './restaurantData'

interface Order {
  id: string;
  restaurant: string;
  customer: string;
  items: string;
  status: 'PENDING' | 'PREPARING' | 'READY' | 'OUT FOR DELIVERY' | 'DELIVERED';
  time: string;
  driver: string;
}

const cobolPrograms = {
  PATTYFOOD: `       IDENTIFICATION DIVISION.
       PROGRAM-ID. PATTYFOOD.
       AUTHOR. PATTY COBOL-PROGRAMMER.
       DATE-WRITTEN. 09/05/2025.
       
       ENVIRONMENT DIVISION.
       INPUT-OUTPUT SECTION.
       FILE-CONTROL.
           SELECT ORDER-FILE ASSIGN TO 'ORDERS.DAT'
           ORGANIZATION IS SEQUENTIAL
           ACCESS MODE IS SEQUENTIAL.
           
       DATA DIVISION.
       FILE SECTION.
       FD ORDER-FILE.
       01 ORDER-RECORD.
           05 ORDER-ID         PIC X(5).
           05 RESTAURANT-NAME  PIC X(30).
           05 CUSTOMER-NAME    PIC X(30).
           05 ORDER-ITEMS      PIC X(50).
           05 ORDER-STATUS     PIC X(15).
           05 ORDER-TIME       PIC X(8).
           05 DRIVER-NAME      PIC X(15).
           
       WORKING-STORAGE SECTION.
       01 WS-ORDER-COUNT       PIC 9(3) VALUE 0.
       01 WS-TOTAL-REVENUE     PIC 9(7)V99 VALUE 0.
       01 WS-EOF-FLAG          PIC X VALUE 'N'.
       
       PROCEDURE DIVISION.
       MAIN-PROGRAM.
           PERFORM INITIALIZE-PROGRAM
           PERFORM PROCESS-ORDERS
           PERFORM DISPLAY-STATISTICS
           STOP RUN.
           
       INITIALIZE-PROGRAM.
           DISPLAY 'PATTY''S UBER EATS TRACKING SYSTEM'
           DISPLAY 'INITIALIZING COBOL RUNTIME...'
           OPEN INPUT ORDER-FILE.
           
       PROCESS-ORDERS.
           PERFORM UNTIL WS-EOF-FLAG = 'Y'
               READ ORDER-FILE
                   AT END MOVE 'Y' TO WS-EOF-FLAG
                   NOT AT END PERFORM PROCESS-ORDER-RECORD
               END-READ
           END-PERFORM
           CLOSE ORDER-FILE.
           
       PROCESS-ORDER-RECORD.
           ADD 1 TO WS-ORDER-COUNT
           DISPLAY 'PROCESSING ORDER: ' ORDER-ID
           EVALUATE ORDER-STATUS
               WHEN 'PENDING'
                   DISPLAY 'STATUS: WAITING FOR RESTAURANT'
               WHEN 'PREPARING'
                   DISPLAY 'STATUS: BEING PREPARED'
               WHEN 'READY'
                   DISPLAY 'STATUS: READY FOR PICKUP'
               WHEN 'DELIVERED'
                   DISPLAY 'STATUS: SUCCESSFULLY DELIVERED'
           END-EVALUATE.
           
       DISPLAY-STATISTICS.
           DISPLAY 'TOTAL ORDERS PROCESSED: ' WS-ORDER-COUNT
           DISPLAY 'SYSTEM STATUS: OPERATIONAL'
           DISPLAY 'END OF PROGRAM EXECUTION'.`,
  
  REPORTS: `       IDENTIFICATION DIVISION.
       PROGRAM-ID. REPORTS.
       AUTHOR. PATTY COBOL-PROGRAMMER.
       
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 REPORT-HEADER.
           05 FILLER PIC X(50) VALUE 
              'UBER EATS DAILY REPORT - GENERATED BY COBOL'.
       01 REPORT-LINE.
           05 ORDER-COUNT PIC Z(3).
           05 FILLER PIC X(5) VALUE ' | '.
           05 REVENUE PIC $$$,$$9.99.
           
       PROCEDURE DIVISION.
       GENERATE-REPORT.
           DISPLAY REPORT-HEADER
           DISPLAY 'ORDERS TODAY: 15'
           DISPLAY 'REVENUE: $1,247.50'
           DISPLAY 'AVG DELIVERY TIME: 22 MINUTES'
           STOP RUN.`,
           
  UTILS: `       IDENTIFICATION DIVISION.
       PROGRAM-ID. UTILS.
       
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 CURRENT-TIME PIC X(8).
       01 CURRENT-DATE PIC X(8).
       
       PROCEDURE DIVISION.
       GET-TIMESTAMP.
           ACCEPT CURRENT-TIME FROM TIME
           ACCEPT CURRENT-DATE FROM DATE
           DISPLAY 'TIMESTAMP: ' CURRENT-DATE ' ' CURRENT-TIME
           EXIT PROGRAM.`
};

function App() {
  const [currentView, setCurrentView] = useState('main');
  const [currentTime, setCurrentTime] = useState('');
  const [commandInput, setCommandInput] = useState('');
  const [currentProgram, setCurrentProgram] = useState('PATTYFOOD');
  const [orders, setOrders] = useState<Order[]>([
    {
      id: 'UE001',
      restaurant: 'MCDONALDS MAIN ST',
      customer: 'JOHN SMITH',
      items: 'BIG MAC, FRIES, COKE',
      status: 'PREPARING',
      time: '14:25:30',
      driver: 'MIKE_D'
    },
    {
      id: 'UE002',
      restaurant: 'PIZZA HUT DOWNTOWN',
      customer: 'JANE DOE',
      items: 'PEPPERONI PIZZA LG',
      status: 'READY',
      time: '14:18:45',
      driver: 'SARAH_K'
    },
    {
      id: 'UE003',
      restaurant: 'STARBUCKS 5TH AVE',
      customer: 'BOB WILSON',
      items: 'LATTE, MUFFIN',
      status: 'DELIVERED',
      time: '14:05:12',
      driver: 'TOM_R'
    }
  ]);

  const commandInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const updateTime = () => {
      const now = new Date();
      setCurrentTime(now.toLocaleTimeString('en-US', { hour12: false }));
    };
    
    updateTime();
    const interval = setInterval(updateTime, 1000);
    
    return () => clearInterval(interval);
  }, []);

  const handleCommand = (event: React.KeyboardEvent) => {
    if (event.key === 'Enter') {
      const command = commandInput.toLowerCase().trim();
      
      switch (command) {
        case '1':
        case 'orders':
          setCurrentView('orders');
          break;
        case '2':
        case 'stats':
          setCurrentView('stats');
          break;
        case '3':
        case 'add':
          setCurrentView('add');
          break;
        case '4':
        case 'update':
          setCurrentView('update');
          break;
        case '5':
        case 'help':
          setCurrentView('help');
          break;
        case 'cobol':
        case 'code':
          setCurrentView('cobol');
          break;
        case 'restaurant':
        case 'manage':
          setCurrentView('restaurant-manager');
          break;
        case '9':
        case 'exit':
          if (window.confirm('EXIT PATTY\'S FOOD TRACKING APP?')) {
            alert('THANK YOU FOR USING PATTY\'S FOOD TRACKER\nLOGGING OFF TN3270...\nSESSION TERMINATED');
          }
          break;
        case 'clear':
          setCurrentView('main');
          break;
        case 'time':
          alert(`CURRENT SYSTEM TIME: ${currentTime}`);
          break;
        default:
          alert(`UNKNOWN COMMAND: ${command.toUpperCase()}\nTYPE 'HELP' FOR AVAILABLE COMMANDS`);
      }
      
      setCommandInput('');
    }
  };

  const addRandomOrder = () => {
    const customers = ['ALICE JOHNSON', 'ROBERT BROWN', 'MARY DAVIS', 'JAMES WILSON', 'LINDA GARCIA'];
    const drivers = ['ALEX_M', 'JENNY_L', 'CARLOS_R', 'DIANA_K', 'FRANK_S'];
    
    const randomRestaurant = getRandomRestaurant();
    const randomMenuItem = randomRestaurant.menuItems[Math.floor(Math.random() * randomRestaurant.menuItems.length)];
    
    const newOrder: Order = {
      id: `UE${String(orders.length + 1).padStart(3, '0')}`,
      restaurant: randomRestaurant.name,
      customer: customers[Math.floor(Math.random() * customers.length)],
      items: randomMenuItem,
      status: 'PENDING',
      time: new Date().toLocaleTimeString('en-US', { hour12: false }),
      driver: drivers[Math.floor(Math.random() * drivers.length)]
    };
    
    setOrders([...orders, newOrder]);
    alert(`ORDER ${newOrder.id} ADDED SUCCESSFULLY`);
  };

  const updateOrderStatus = (orderId: string) => {
    const statusOptions: Order['status'][] = ['PENDING', 'PREPARING', 'READY', 'OUT FOR DELIVERY', 'DELIVERED'];
    const currentOrder = orders.find(o => o.id === orderId);
    
    if (currentOrder) {
      const currentIndex = statusOptions.indexOf(currentOrder.status);
      const nextStatus = statusOptions[Math.min(currentIndex + 1, statusOptions.length - 1)];
      
      setOrders(orders.map(order => 
        order.id === orderId ? { ...order, status: nextStatus } : order
      ));
      
      alert(`ORDER ${orderId} STATUS UPDATED TO: ${nextStatus}`);
    }
  };

  const renderContent = () => {
    switch (currentView) {
      case 'orders':
        return (
          <div className="order-display" style={{ display: 'block' }}>
            <div className="menu-title">ACTIVE UBER EATS ORDERS - REAL TIME STATUS</div>
            <table className="order-table">
              <thead>
                <tr>
                  <th>ORDER-ID</th>
                  <th>RESTAURANT</th>
                  <th>CUSTOMER</th>
                  <th>ITEMS</th>
                  <th>STATUS</th>
                  <th>TIME</th>
                  <th>DRIVER</th>
                  <th>ACTION</th>
                </tr>
              </thead>
              <tbody>
                {orders.map(order => (
                  <tr key={order.id}>
                    <td>{order.id}</td>
                    <td>{order.restaurant}</td>
                    <td>{order.customer}</td>
                    <td>{order.items}</td>
                    <td className={`status-${order.status.toLowerCase().replace(' ', '-')}`}>{order.status}</td>
                    <td>{order.time}</td>
                    <td>{order.driver}</td>
                    <td>
                      <button 
                        onClick={() => updateOrderStatus(order.id)}
                        style={{ 
                          background: '#004400', 
                          color: '#00ff00', 
                          border: '1px solid #00ff00',
                          padding: '2px 6px',
                          cursor: 'pointer',
                          fontFamily: 'inherit',
                          fontSize: '12px'
                        }}
                      >
                        UPDATE
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div style={{ marginTop: '15px', color: '#ffff00' }}>
              TOTAL ORDERS: {orders.length} | PENDING: {orders.filter(o => o.status === 'PENDING').length} | 
              PREPARING: {orders.filter(o => o.status === 'PREPARING').length} | 
              READY: {orders.filter(o => o.status === 'READY').length} | 
              DELIVERED: {orders.filter(o => o.status === 'DELIVERED').length}
            </div>
          </div>
        );

      case 'stats':
        return (
          <div className="menu-section">
            <div className="menu-title">UBER EATS STATISTICS REPORT</div>
            <div style={{ marginTop: '15px' }}>
              <div>TOTAL ORDERS TODAY:     {orders.length}</div>
              <div>AVG DELIVERY TIME:     22:15</div>
              <div>TOP RESTAURANT:        {restaurants[0]?.name || 'MCDONALDS MAIN ST'}</div>
              <div>ACTIVE DRIVERS:        15</div>
              <div>COMPLETION RATE:       94.2%</div>
              <div>CUSTOMER RATING:       4.7/5.0</div>
            </div>
            <div style={{ marginTop: '20px', color: '#00ffff' }}>
              HOURLY BREAKDOWN:
              <div style={{ marginLeft: '20px', marginTop: '10px' }}>
                <div>12:00-13:00  ████████░░  8 ORDERS</div>
                <div>13:00-14:00  ██████████  12 ORDERS</div>
                <div>14:00-15:00  ███████░░░  9 ORDERS</div>
                <div>15:00-16:00  █████░░░░░  5 ORDERS</div>
              </div>
            </div>
          </div>
        );

      case 'add':
        return (
          <div className="menu-section">
            <div className="menu-title">ADD NEW UBER EATS ORDER</div>
            <div style={{ marginTop: '15px', color: '#00ffff' }}>
              <div>ORDER ID......: UE{String(orders.length + 1).padStart(3, '0')}</div>
              <div>RESTAURANT.....: [RANDOMLY GENERATED]</div>
              <div>CUSTOMER.......: [RANDOMLY GENERATED]</div>
              <div>ITEMS..........: [RANDOMLY GENERATED]</div>
              <div>DRIVER.........: [RANDOMLY ASSIGNED]</div>
              <div>STATUS.........: PENDING</div>
              <div>TIME...........: {currentTime}</div>
            </div>
            <div style={{ marginTop: '20px', color: '#ffff00' }}>
              <button 
                onClick={addRandomOrder}
                style={{ 
                  background: '#004400', 
                  color: '#00ff00', 
                  border: '1px solid #00ff00',
                  padding: '8px 16px',
                  cursor: 'pointer',
                  fontFamily: 'inherit',
                  fontSize: '14px',
                  marginRight: '10px'
                }}
              >
                GENERATE RANDOM ORDER
              </button>
              PRESS BUTTON TO CREATE NEW ORDER OR TYPE 'CLEAR' TO RETURN
            </div>
          </div>
        );

      case 'update':
        return (
          <div className="menu-section">
            <div className="menu-title">UPDATE ORDER STATUS</div>
            <div style={{ marginTop: '15px' }}>
              <div>CLICK UPDATE BUTTON IN ORDERS VIEW TO ADVANCE STATUS</div>
              <div style={{ marginTop: '10px', color: '#00ffff' }}>
                AVAILABLE STATUS PROGRESSION:
                <div style={{ marginLeft: '20px' }}>
                  <div>1 = PENDING → PREPARING</div>
                  <div>2 = PREPARING → READY</div>
                  <div>3 = READY → OUT FOR DELIVERY</div>
                  <div>4 = OUT FOR DELIVERY → DELIVERED</div>
                </div>
              </div>
            </div>
            <div style={{ marginTop: '20px', color: '#ffff00' }}>
              TYPE 'ORDERS' TO VIEW AND UPDATE ORDER STATUS
            </div>
          </div>
        );

      case 'help':
        return (
          <div className="menu-section">
            <div className="menu-title">COBOL UBER EATS TRACKER - HELP SYSTEM</div>
            <div style={{ marginTop: '15px', color: '#00ffff' }}>
              AVAILABLE COMMANDS:
              <div style={{ marginLeft: '20px', marginTop: '10px' }}>
                <div>1 or ORDERS    - Display active orders</div>
                <div>2 or STATS     - Show statistics</div>
                <div>3 or ADD       - Add new order</div>
                <div>4 or UPDATE    - Update order status</div>
                <div>5 or HELP      - This help screen</div>
                <div>COBOL or CODE  - View COBOL source code</div>
                <div>RESTAURANT     - Restaurant management</div>
                <div>9 or EXIT      - Exit application</div>
                <div>CLEAR          - Clear screen</div>
                <div>TIME           - Show current time</div>
              </div>
            </div>
            <div style={{ marginTop: '20px', color: '#ffff00' }}>
              FUNCTION KEYS:
              <div style={{ marginLeft: '20px' }}>
                <div>PF1  = HELP    PF3  = EXIT</div>
                <div>PF7  = UP      PF8  = DOWN</div>
                <div>PF12 = CANCEL</div>
              </div>
            </div>
          </div>
        );

      case 'cobol':
        return (
          <div className="menu-section">
            <div className="menu-title">COBOL SOURCE LIBRARY - PATTY'S FOOD TRACKER</div>
            <div style={{ marginTop: '10px', color: '#00ffff' }}>
              SELECT PROGRAM TO EDIT:
            </div>
            <div style={{ margin: '10px 0' }}>
              <select 
                value={currentProgram}
                onChange={(e) => setCurrentProgram(e.target.value)}
                style={{ 
                  background: '#003300', 
                  color: '#00ff00', 
                  border: '1px solid #00ff00', 
                  padding: '5px', 
                  fontFamily: 'inherit' 
                }}
              >
                <option value="PATTYFOOD">PATTYFOOD.COB - Main Program (350+ lines)</option>
                <option value="REPORTS">REPORTS.COB - Reports Module (50+ lines)</option>
                <option value="UTILS">UTILS.COB - Utility Functions (30+ lines)</option>
              </select>
            </div>
            <div style={{ color: '#00ffff' }}>
              DATASET: COBOL.SOURCE.{currentProgram}(MAIN) - EDIT MODE
            </div>
            <div className="cobol-editor">
              <textarea 
                className="cobol-textarea" 
                value={cobolPrograms[currentProgram as keyof typeof cobolPrograms]}
                readOnly
                spellCheck={false}
              />
            </div>
            <div style={{ color: '#ffff00', marginTop: '10px' }}>
              PROGRAM STATS: {cobolPrograms[currentProgram as keyof typeof cobolPrograms].split('\n').length} LINES | 
              {Math.round(cobolPrograms[currentProgram as keyof typeof cobolPrograms].length / 1024)}KB | LAST MODIFIED: TODAY
            </div>
            <div style={{ color: '#ffff00' }}>
              COMMANDS: SAVE | COMPILE | RESET | SYNTAX-CHECK | SWITCH-PROGRAM
            </div>
          </div>
        );

      case 'restaurant-manager':
        return (
          <div className="menu-section">
            <div className="menu-title">RESTAURANT MANAGEMENT SYSTEM</div>
            <div style={{ marginTop: '15px', color: '#00ffff' }}>
              CURRENT RESTAURANTS IN DATABASE:
            </div>
            <div style={{ marginTop: '10px', marginLeft: '20px' }}>
              {restaurants.map((restaurant, index) => (
                <div key={restaurant.id} style={{ marginBottom: '5px' }}>
                  <div style={{ color: '#ffff00' }}>
                    {index + 1}. {restaurant.name}
                  </div>
                  <div style={{ marginLeft: '20px', fontSize: '12px' }}>
                    ADDRESS: {restaurant.address} | PHONE: {restaurant.phone}
                  </div>
                  <div style={{ marginLeft: '20px', fontSize: '12px' }}>
                    CUISINE: {restaurant.cuisine} | MENU: {restaurant.menuItems.join(', ')}
                  </div>
                </div>
              ))}
            </div>
            <div style={{ marginTop: '20px', color: '#ffff00' }}>
              TO ADD NEW RESTAURANTS:
              <div style={{ marginLeft: '20px', marginTop: '10px' }}>
                <div>1. EDIT FILE: src/restaurantData.ts</div>
                <div>2. ADD RESTAURANT TO ARRAY FOLLOWING COBOL FORMAT</div>
                <div>3. USE ALL CAPS AND UNDERSCORES FOR IDS</div>
                <div>4. SAVE FILE AND RESTART APPLICATION</div>
              </div>
            </div>
            <div style={{ marginTop: '15px', color: '#00ff00' }}>
              WEB INTERFACE: Access http://localhost:3000 for GUI editing
            </div>
            <div style={{ marginTop: '10px', color: '#ffff00' }}>
              TYPE 'CLEAR' TO RETURN TO MAIN MENU
            </div>
          </div>
        );

      default:
        return (
          <div className="menu-section">
            <div className="menu-title">SYSTEM STATUS:</div>
            <div>COBOL RUNTIME: ACTIVE</div>
            <div>TN3270 CONNECTION: ESTABLISHED</div>
            <div>UBER EATS API: SIMULATED</div>
            <div>DATABASE: MVS/TSO CONNECTED</div>
          </div>
        );
    }
  };

  return (
    <div className="terminal">
      <div className="header">
        IBM 3270 TERMINAL - COBOL UBER EATS TRACKING SYSTEM V2.1
      </div>
      
      <div className="screen">
        <div className="cobol-header">
          <pre>
{` ██████╗ ██████╗ ██████╗  ██████╗ ██╗         ██╗   ██╗██████╗ ███████╗██████╗ 
██╔════╝██╔═══██╗██╔══██╗██╔═══██╗██║         ██║   ██║██╔══██╗██╔════╝██╔══██╗
██║     ██║   ██║██████╔╝██║   ██║██║         ██║   ██║██████╔╝█████╗  ██████╔╝
██║     ██║   ██║██╔══██╗██║   ██║██║         ██║   ██║██╔══██╗██╔══╝  ██╔══██╗
╚██████╗╚██████╔╝██████╔╝╚██████╔╝███████╗    ╚██████╔╝██████╔╝███████╗██║  ██║
 ╚═════╝ ╚═════╝ ╚═════╝  ╚═════╝ ╚══════╝     ╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝`}
          </pre>
          <div>EATS TRACKING SYSTEM - MAINFRAME DIVISION</div>
        </div>
        
        <div className="menu-section">
          <div className="menu-title">MAIN MENU OPTIONS:</div>
          <div className="menu-item" onClick={() => setCurrentView('orders')}>1. VIEW ACTIVE ORDERS</div>
          <div className="menu-item" onClick={() => setCurrentView('stats')}>2. ORDER STATISTICS</div>
          <div className="menu-item" onClick={() => setCurrentView('add')}>3. ADD NEW ORDER</div>
          <div className="menu-item" onClick={() => setCurrentView('update')}>4. UPDATE ORDER STATUS</div>
          <div className="menu-item" onClick={() => setCurrentView('help')}>5. HELP</div>
          <div className="menu-item" onClick={() => setCurrentView('cobol')}>C. VIEW COBOL SOURCE</div>
          <div className="menu-item" onClick={() => setCurrentView('restaurant-manager')}>R. RESTAURANT MANAGER</div>
          <div className="menu-item" onClick={() => {
            if (window.confirm('EXIT PATTY\'S FOOD TRACKING APP?')) {
              alert('THANK YOU FOR USING PATTY\'S FOOD TRACKER\nLOGGING OFF TN3270...\nSESSION TERMINATED');
            }
          }}>9. EXIT</div>
        </div>
        
        <div id="content-area">
          {renderContent()}
        </div>
        
        <div className="input-line">
          COMMAND ===&gt; 
          <input
            ref={commandInputRef}
            type="text" 
            className="command-input" 
            value={commandInput}
            onChange={(e) => setCommandInput(e.target.value)}
            onKeyPress={handleCommand}
            maxLength={72}
          />
          <span className="cursor">_</span>
        </div>
      </div>
      
      <div className="status-bar">
        PF1=HELP  PF3=EXIT  PF7=UP  PF8=DOWN  PF12=CANCEL | LOGGED IN: COBOL_USER | TIME: {currentTime}
      </div>
    </div>
  );
}

export default App
